//action - snackbar
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

//action - user
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';


//actions - chat
export const SET_USERS = 'SET_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_CONVERSATION_ID = 'SET_CONVERSATION_ID';
export const INC_PAGE ='INC_PAGE';
export const RESET_PAGE='RESET_PAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const PUSH_NEW_MESSAGE = 'PUSH_NEW_MESSAGE';
export const SET_TO_INITIAL_STATE = 'SET_TO_INITIAL_STATE';
export const SET_NEW_MESSAGE_NOTIFICATION_IN_USER_LIST = 'SET_NEW_MESSAGE_NOTIFICATION_IN_USER_LIST';
export const CLEAR_NEW_MESSAGE_NOTIFICATION_IN_USER_LIST = 'CLEAR_NEW_MESSAGE_NOTIFICATION_IN_USER_LIST';
export const APPEND_OLDER_MESSAGES = 'APPEND_OLDER_MESSAGES';
export const SET_HAS_MORE = 'SET_HAS_MORE';
export const RESET_CONVERSATIONS = 'RESET_CONVERSATIONS';
export const RESET_CHAT_STORE = 'RESET_CHAT_STORE';







// XOX Game

export const START_GAME = 'START_GAME'